version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "type/chore"
      - "area/ci"

  - package-ecosystem: "pub"
    directory: "/applications/client_app"
    schedule:
      interval: "weekly"
    labels:
      - "type/chore"
      - "area/flutter"

  - package-ecosystem: "gomod"
    directory: "/services/api"
    schedule:
      interval: "weekly"
    labels:
      - "type/chore"
      - "area/go"
