version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

    open-pull-requests-limit: 10

    reviewers:
      - "Dinmukhamed Nurkaliyev"

  - package-ecosystem: "pub"
    directory: "/applications/client_app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "pub"
    directory: "/packages/core_ui"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/services/api"
    schedule:
      interval: "weekly"
