name: Go Lint

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check if directory exists
        id: check_dir
        run: |
          TARGET_DIR="services/api"
          if [ -d "$TARGET_DIR" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "✅ Directory $TARGET_DIR found."
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "⚠️ Directory $TARGET_DIR not found. Skipping linting."
          fi

      - uses: ./.github/actions/setup-go/
        if: steps.check_dir.outputs.exists == 'true'

      - name: Run GolangCI-Lint
        if: steps.check_dir.outputs.exists == 'true'
        uses: golangci/golangci-lint-action@v9.2.0
        with:
          version: v2.7.0
          working-directory: services/api
          args: --timeout=10m --out-format=colored-line-number
