name: "Check: Go Lint"

on:
  workflow_call:
    secrets:
      PAT:
        required: false

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-go/
        id: setup
        with:
          working-directory: services/api
          token: ${{ secrets.PAT }}

      - name: Run GolangCI-Lint
        if: steps.setup.outputs.installed == 'true'
        uses: golangci/golangci-lint-action@v9.2.0
        with:
          version: 2.7.0
          working-directory: services/api
          args: --timeout=5m --out-format=colored-line-number
