name: Go Test & Coverage

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: false
      PAT:
        required: false

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6.0.1

      - uses: ./.github/actions/setup-go/
        id: setup
        with:
          working-directory: services/api
          token: ${{ secrets.PAT }}

      - name: Run Tests
        if: steps.setup.outputs.installed == 'true'
        working-directory: services/api
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
          go test ./... -race -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage
        if: steps.setup.outputs.installed == 'true'
        uses: codecov/codecov-action@v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./services/api/coverage.txt
          fail_ci_if_error: true
          verbose: true
